hadoop:
  commons:
    zookeeper:
      config:
        zookeeper_quorum: hebsjzx-schbase-master-47-158,hebsjzx-schbase-master-47-75,hebsjzx-schbase-master-47-96 #zk集群地址
    kerberos:
      config:
        keytab-path: /home/bdi/api/cmit_wzzjc_wzjd.keytab #密钥配置
        kerberos-conf-path: /home/bdi/api/krb5.conf #krb5
        kerberos-user: cmit_wzzjc_wzjd #zk用户
        zookeeper-default-server-principal: cmit_wzzjc_wzjd@SCKDC #zk用户主体
        principal: hbase/_HOST@SCKDC #hbase 主体
        znode-parent: /hbase-secure
thread-pool:
  core_pool_size: 3 #初始线程数
  max_pool_size: 10 #最大线程数
  queue_capacity: 512 #队列数
  keep_alive_seconds: 10 #等待时间
  hread_name_prefix: query-hbase-thread-pool-%d #线程名称
encryp-decryp:
   url: http://10.252.15.211:9010/Adapter/getKey.do #sm4服务地址
server:
  servlet:
    context-path: /hbase-query
