hadoop:
  commons:
    zookeeper:
      config:
        zookeeper_quorum: hebsjzx-schbase-master-47-158,hebsjzx-schbase-master-47-75,hebsjzx-schbase-master-47-96 #zk集群地址
    kerberos:
      config:
        keytab-path: /home/cmit_detail/api/cmit_wzzjc_wzjd.keytab #keytab文件路径
        kerberos-conf-path: /home/cmit_detail/api/krb5.conf #krb5
        kerberos-user: cmit_wzzjc_wzjd #zk用户
        zookeeper-default-server-principal: cmit_wzzjc_wzjd@SCKDC #zk主体
        principal: hbase/_HOST@SCKDC #hbase主体
        znode-parent: /hbase-secure
thread-pool:
  core_pool_size: 3 #初始线程数
  max_pool_size: 10 #最大线程数
  queue_capacity: 512 #队列数
  keep_alive_seconds: 10 #等待时间
  thread_name_prefix: query-hbase-thread-pool-%d #线程名称
encryp-decryp:
  url: http://10.252.15.211:9010/Adapter/getKey.do #sm4 加解密服务地址
xdr:
  router-config:
    #effective-time: 20210909 #建表规则生效时间
    old-time-interval: #旧规则-生效时间之前的规则
      - start-date: 00
        end-date: 08
      - start-date: 08
        end-date: 12
      - start-date: 12
        end-date: 18
      - start-date: 18
        end-date: 24
    newer-time-interval: #新规则-生效时间之后的规则
      - start-date: 00
        end-date: 10
      - start-date: 10
        end-date: 17
      - start-date: 17
        end-date: 20
      - start-date: 20
        end-date: 24
